# Generated by Django 5.0.2 on 2024-02-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='date',
        ),
    ]
