# Generated by Django 5.0.2 on 2024-03-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_product_is_fablock_ace'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_smart_fablock',
            field=models.BooleanField(default=False),
        ),
    ]
