# Generated by Django 5.0.2 on 2024-03-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_product_is_smart_fablock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_smart_fablock',
            new_name='is_smart_fablock_plus',
        ),
    ]
