# Generated by Django 5.0.2 on 2024-03-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_product_main_image_product_sub_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
