# Generated by Django 5.0.2 on 2024-03-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_product_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
