# Generated by Django 5.0.2 on 2024-03-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_updates_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
