# Generated by Django 5.0.2 on 2024-03-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_updates_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealershipInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('business', models.CharField(max_length=200)),
                ('year_of_experience', models.CharField(max_length=150)),
                ('brand_handled', models.CharField(max_length=200)),
                ('annual_turnover', models.CharField(max_length=200)),
                ('why_loqz', models.TextField()),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.dealershipinterest')),
            ],
        ),
    ]
