# Generated by Django 5.0.2 on 2024-03-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_team_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_fablock_ace',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_smart_fablock_plus',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('fablock_ace', 'Fablock Ace'), ('smart_fablock_plus', 'Smart Fablock Plus')], max_length=128, null=True),
        ),
    ]
