# Generated by Django 5.0.2 on 2024-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_product_is_fablock_ace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='detail_image',
            field=models.ImageField(default=1, upload_to='updates_/detail'),
            preserve_default=False,
        ),
    ]
