# Generated by Django 5.0.2 on 2024-03-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_updates_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='interest',
            field=models.ForeignKey(blank=True, choices=[('interest', 'Interest')], null=True, on_delete=django.db.models.deletion.CASCADE, to='web.dealershipinterest'),
        ),
    ]
