# Generated by Django 5.0.2 on 2024-03-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_dealership_interest_delete_dealershipinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='whatsapp_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
